apps/new/urls.py
from django.contrib import admin
from django.urls import path

from .views import *
app_name = 'new'
urlpatterns = [
    path('newlist/', NewList.as_view(), name='new_list'),
    path('article/<str:classify>/<int:new_id>/', NewArticle.as_view(), name='article'),
]

apps/safe/urls.py
from django.urls import path

from .views import Safe
app_name = 'safe'
urlpatterns = [
    path('', Safe.as_view(), name='index')
]

apps/server/urls.py
from django.urls import path

from .views import *
app_name = 'server'
urlpatterns = [
    path('', Server.as_view(), name='index')
]

xingzhiyu/urls.py
from django.conf import settings
from django.conf.urls.static import static


from django.contrib import admin
from django.urls import path, include,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.index.urls',namespace='index')),
    path('success_case/', include('apps.success_case.urls', namespace='success_case')),
    path('server/', include('apps.server.urls',namespace='server')),
    path('new/', include('apps.new.urls',namespace='new')),
    path('safe/', include('apps.safe.urls',namespace='safe')),
    path('about_us/', include('apps.about_us.urls',namespace='about_us')),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/new/models.py
from datetime import datetime

from django.db import models
from django.utils.html import format_html

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


# 新闻
class New(models.Model):
    CLASSIFYS = (
        ('announcement', '网站公告'),
        ('industry_information', '行业资讯'),
        ('media_report', '媒体报道'),
    )
    classify = models.CharField(verbose_name='文章分类', choices=CLASSIFYS, max_length=36)
    image = models.ImageField(max_length=200, upload_to='new/%Y/%m', verbose_name='封面')
    title = models.CharField(verbose_name='文章标题', max_length=64)
    author = models.CharField(verbose_name='文章作者', max_length=32, default='YuKalix')
    intro = models.CharField(verbose_name='文章简介', max_length=300, default='')
    content = RichTextUploadingField(verbose_name='文章内容', default='')
    read_num = models.PositiveIntegerField(verbose_name='文章数量', default=0)
    add_time = models.DateTimeField(verbose_name='时间', auto_now_add=datetime.now())
    is_top = models.BooleanField(verbose_name='是否置顶(首页)', default=False)
    is_delete = models.BooleanField(verbose_name='是否展示', default=True)

    def new_image_url(self):
        return format_html( '<img src="{0}" width="100px"/>', self.image.url)
    new_image_url.short_description = u'封面'

    class Meta:
        verbose_name = '新闻'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

apps/safe/models.py
from django.db import models

# Create your models here.

apps/server/models.py
from django.db import models

# Create your models here.

apps/success_case/models.py
from datetime import datetime

from django.db import models
from django.utils.html import format_html
# Create your models here.


# 案例
class Case(models.Model):
    image = models.ImageField(max_length=200, upload_to='success_case/%Y/%m', verbose_name='展示图')
    describe = models.CharField(verbose_name='案列简介', max_length=50, default='')
    url = models.URLField(verbose_name='案例链接')
    add_time = models.DateTimeField(verbose_name='时间', auto_now_add=datetime.now())
    is_display = models.BooleanField(verbose_name='是否展示', default=True)

    def case_image_url(self):
        return format_html( '<img src="{0}" width="100px"/>', self.image.url)
    case_image_url.short_description = u'封面'

    class Meta:
        verbose_name = '案例'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.describe

apps/new/views.py
from django.shortcuts import render
from django.views.generic import View

from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
from .models import *

# 由于设计初失误,emmmm还得稍微引入
from apps.index.models import Information,Logo


# 新闻列表
class NewList(View):
    def get(self, request):
        # 获取信息
        information = Information.objects.first()
        # 获取logo
        logo = Logo.objects.first()


        # 获取所有classify
        classifies = New.CLASSIFYS
        # 取到的是元组,序列化成dict
        classifies = dict(classifies)

        # 获取新闻
        # 获取当前页面文章类别
        classify = request.GET.get('classify', '')
        print(classify)
        if classify:
            news = New.objects.filter(classify=classify, is_delete=True)
        else:
            news = New.objects.all().filter(is_delete=True)


        # 分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        # 这里指从allorg中取五个出来，每页显示5个
        p = Paginator(news,5)
        news = p.page(page)



        return render(request, 'new_list.html', {
            'information': information,
            'logo': logo,

            'classifies':classifies,
            'news': news,
        })


# 文章
class NewArticle(View):
    def get(self, request, classify, new_id):
        # 获取信息
        information = Information.objects.first()
        # 获取logo
        logo = Logo.objects.first()

        # 获取点击文章
        article = New.objects.filter(id=new_id)
        # 浏览该文章浏览量+1
        read_num = article[0].read_num + 1
        article.update(read_num=read_num)


        return render(request, 'new.html', {
            'information': information,
            'logo': logo,

            'article': article[0],
        })

apps/safe/views.py
from django.shortcuts import render
from django.views.generic import View

# Create your views here.
# 由于设计初失误,emmmm还得稍微引入
from apps.index.models import Information,Logo

class Safe(View):
    def get(self, request):
        # 获取信息
        information = Information.objects.first()
        # 获取logo
        logo = Logo.objects.first()


        return render(request, 'safe.html', {
            'information': information,
            'logo': logo,
        })

apps/server/views.py
from django.shortcuts import render
from django.views.generic import View

# Create your views here.
# 由于设计初失误,emmmm还得稍微引入
from apps.index.models import Information,Logo

class Server(View):
    def get(self, request):
        # 获取信息
        information = Information.objects.first()
        # 获取logo
        logo = Logo.objects.first()


        return render(request, 'server.html', {
            'information': information,
            'logo': logo,
        })

apps/success_case/views.py
from django.shortcuts import render
from django.views.generic import View


from pure_pagination import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
from .models import Case
# 由于设计初失误,emmmm还得稍微引入
from apps.index.models import Information,Logo

class SuccessCase(View):
    def get(self, request):
        # 获取信息
        information = Information.objects.first()
        # 获取logo
        logo = Logo.objects.first()

        # 获取案例
        cases = Case.objects.filter(is_display=True).order_by('-add_time')
        new_caases = cases[:8]
        # 分页
        # try:
        #     page = request.GET.get('page', 1)
        # except PageNotAnInteger:
        #     page = 1
        # # 这里指从中取五个出来，每页显示5个
        # p = Paginator(cases, 1)
        # cases = p.page(page)


        return render(request, 'success_case.html', {
            'information': information,
            'logo': logo,
            'new_caases': new_caases,
            'cases': cases,
        })

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="keywords" content="{{ information.name }}">
    <meta name="author" content="YuKalix">
    <link rel="icon" href="{% static 'images/logo.png' %}">
    <title>
        {% block title %}
        {% endblock %}----{{ information.name }}
    </title>

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/min.css' %}">
    {% block css %}{% endblock %}

    <script type="text/javascript" src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/menu_jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/myjs.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slides.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jq_scroll.js' %}"></script>
    {% block js %}{% endblock %}

</head>
{% include 'header.html' %}
{% block body %}

{% endblock %}
{% include 'footer.html' %}
</html>

templates/footer.html
<div id="footer" class="item">
	<div class="inner wl">
		<a href="{% url 'index:index' %}">首页</a>|
        <a href="" onclick="alert('暂未开发,敬请期待')">产品中心</a>|
        <a href="{% url 'success_case:index' %}">成功案例</a>|
        <a href="{% url 'server:index' %}">服务项目</a>|
        <a href="{% url 'safe:index' %}">安全理念</a>|
        <a href="{% url 'new:new_list' %}">新闻动态</a>|
        <a href="{% url 'about_us:index' %}">关于我们</a>
{#		<p>#}
{#			公司地址：宁夏 联系电话：17609570714#}
{#            QQ：<a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=705301804&site=qq&menu=yes">705301804</a>#}
{#		</p>#}
		<p>
			{{ information.name }}<br>
            {{ information.icp }}  © 2019-2019<br>
            <a href="http://52ziyu.cn/" target="_blank">YuKalix</a> All Rights Reserved
		</p>
	</div>
</div>

templates/header.html
{% load static %}
<div id="heaher" class="item">
	<div class="inner wl">
		<div class="logo">
			<a href="" title="{{ logo.describe }}"><img src="{{ MEDIA_URL }}{{ logo.image }}" width="200" height="80" alt="这里是公司logo"></a>
		</div>
		<div class="headnav" id="navigate">
			<ul>
				<li><a href="{% url 'index:index' %}">首页</a></li>
				<li><a href="/" onclick="alert('暂未开发,敬请期待')">产品中心</a></li>
				<li><a {% ifequal request.path '/success_case/' %} class="sel" {% endifequal %} href="{% url 'success_case:index' %}">成功案例</a></li>
				<li><a {% ifequal request.path '/server/' %} class="sel" {% endifequal %}href="{% url 'server:index' %}">服务项目</a></li>
				<li><a {% ifequal request.path '/safe/' %} class="sel" {% endifequal %} href="{% url 'safe:index' %}">安全理念</a></li>
				<li><a {% ifequal request.path '/new/newlist/' %} class="sel" {% endifequal %}href="{% url 'new:new_list' %}">新闻动态</a></li>
				<li><a {% ifequal request.path '/about_us/' %} class="sel" {% endifequal %}href="{% url 'about_us:index' %}">关于我们</a></li>
				<li><a href="/admin/" target="_blank">后台</a></li>
			</ul>
		</div>
	</div>
</div>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}首页{% endblock %}

{% block body %}
    <body id="body">

<script type="text/javascript">
    $("#navigate a").each(function(){var e=this.href.toLowerCase().substring(0,this.href.length-5);document.location.href.toLocaleLowerCase().indexOf(e)>-1&&($("#navigate a").removeClass("sel"),$(this).addClass("sel"))});
</script>

<div id="slides" class="visual item">
	<ul class="slides-container">
        {% for banner in banners %}
            <li style="background:url({{ MEDIA_URL }}{{ banner.image }}) center no-repeat">
                <a href="{{ banner.url }}" target="_blank" title="{{ banner.describe }}"></a>
            </li>
        {% endfor %}
	</ul>
	<div class="prev icons">
		<a href="#"></a>
	</div>
	<div class="next icons">
		<a href="#"></a>
	</div>
	<div class="slideControl pagination">
		<span><a href="#" rel="0"></a></span>
        <span><a href="#" rel="1"></a></span>
        <span><a href="#" rel="2"></a></span>
	</div>
</div>
<div class="index-graybox item" id="flow">
	<div class="wl index-graycon">
		<div class="index-announce">
			<a href="{% url 'new:new_list'%}?classify=announcement" class="index-announce-til">最新公告</a>
			<div class="index-announce-inc">
				<div class="announce-info">
					<ul>
                        {% for announcement in announcements %}
                        <li>{{ announcement.title }}</li>
                        {% endfor %}
					</ul>
				</div>
				<div class="announce-btn">
					<a id="announce-btn-up" class="icons btn-up" href="javascript:;" style="cursor:pointer"></a><a id="announce-btn-down" class="icons btn-down" href="javascript:;" style="cursor:pointer"></a>
				</div>
			</div>
			<div class="icons announce-btn-end">
			</div>
		</div>
<!-- 		<div class="index-contact">
			<a target="_blank" href="#"><em class="icons ico-phone"></em>
			<div class="contact-text">
				<p class="con-text">
					<span>咨询热线：</span><em>400-811-4655</em>
				</p>
				<p class="con-arrow">
					<em class="icons ico-con-arrow"></em>
				</p>
			</div>
			</a><a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2880709080&site=qq&menu=yes"><em class="icons ico-qq"></em>
			<div class="contact-text">
				<p class="con-text">
					<span>企业QQ：</span><em>2880709080</em>
				</p>
				<p class="con-arrow">
					<em class="icons ico-con-arrow"></em>
				</p>
			</div>
			</a><a href="mailto:kefu@ixundai.com"><em class="icons ico-msg"></em>
			<div class="contact-text">
				<p class="con-text">
					<span>邮箱地址：</span><em>kefu@ixundai.com</em>
				</p>
				<p class="con-arrow">
					<em class="icons ico-con-arrow"></em>
				</p>
			</div>
			</a>
		</div> -->
		<div class="index-flow">
			<ul>
				<li><em class="icons early"></em>前期策划沟通<br>
				COMMUNICATIONS</li>
				<li><em class="icons design"></em>视觉及交互设计<br>
				VISUAL AND DESIGN</li>
				<li><em class="icons html"></em>前端表现及功能开发<br>
				HTML/CSS/TLoan</li>
				<li><em class="icons test"></em>测试调整阶段<br>
				ADJUSTMENT/TEST</li>
			</ul>
		</div>
	</div>
</div>
<div class="index-aboutbox item" id="about">
	<div class="wl index-aboutcon">
		<div class="slogan f1">
			<div class="fl">
				<span><font class="fs24">远瞻</font>积淀专业</span><span><font class="fs24">专业</font>打造安全</span><span><font class="fs24">安全</font>赢得市场</span>
			</div>
			<div class="fr">
				<span><font class="f24">互联网金融行业领航者</font></span>
			</div>
		</div>
		<div class="firm">
			<div class="font">
				<span class="f2 fs36">About Us</span><br>
				<span class="f2 fs36">&amp;</span><br>
				<span class="f3 fs20">{{ information.name }}</span>
			</div>
			<p class="fs16">
                {{ information.introduce }}
			</p>
		</div>
	</div>
</div>
<div class="box-end icons">
</div>
<div class="wl index-advantagebox item" id="advantage">
	<div class="font">
		<span class="f2 fs36 c1">Our Advantages</span><br>
		<span class="f2 fs36 c1">&amp;</span><br>
		<span class="f3 fs20 c2">我们的优势</span>
	</div>
	<div class="colorcirclemainbox">
		<div class="colorcirclebox">
			<div class="colorcircle col-1">
				<em class="icons"></em>
			</div>
			<p>
				TLoan系统功能完善、稳定、高效、易用、简洁、安全
			</p>
		</div>
		<div class="colorcirclebox">
			<div class="colorcircle col-2">
				<em class="icons"></em>
			</div>
			<p>
				根据特点，全力打造具有知识产权的framework
			</p>
		</div>
		<div class="colorcirclebox">
			<div class="colorcircle col-3">
				<em class="icons"></em>
			</div>
			<p>
				基于C#语言开发，采用标准MVC，能进行集群部署
			</p>
		</div>
		<div class="colorcirclebox">
			<div class="colorcircle col-4">
				<em class="icons"></em>
			</div>
			<p>
				系统具有高扩展性，高效性，很方便根据客户的具体要求进行二次开发
			</p>
		</div>
		<div class="colorcirclebox">
			<div class="colorcircle col-5">
				<em class="icons"></em>
			</div>
			<p>
				精确的数据统计，网站的每笔资金都能找到来源和去向，方便跟踪
			</p>
		</div>
		<div class="colorcirclebox">
			<div class="colorcircle col-6">
				<em class="icons"></em>
			</div>
			<p>
				提供完善的管理机制，从前台页面到账户中心页面交互设计
			</p>
		</div>
		<div class="colorcirclebox">
			<div class="colorcircle col-7">
				<em class="icons"></em>
			</div>
			<p>
				大量使用AJAX局部刷新技术提交和获取数据，减少服务器负担、提升用户体验
			</p>
		</div>
	</div>
</div>
<div class="index-serbox item" id="serve">
	<div class="wl inbox">
		<div class="font">
			<span class="f2 fs36">Our Services</span><br>
			<span class="f2 fs36">&amp;</span><br>
			<span class="f3 fs20">我们的服务</span>
			<p class="lh56 f1 fs16">
				最贴心客服 资深团队 全业务流 多元化 全方位解析
			</p>
		</div>
		<div id="marquee1" class="marqueeleft">
			<div style="width:8000px">
				<ul id="marquee1_1">
                    {% for service in services %}
					<li><a href="{{ service.url }}"><img src="{{ MEDIA_URL }}{{ service.image }}">
					<p>
                        {{ service.describe }}
					</p>
					</a></li>
                    {% endfor %}
				</ul>
				<ul id="marquee1_2">
				</ul>
			</div>
		</div>
		<script type="text/javascript">marqueeStart(1,"left");</script>
	</div>
</div>
<div class="wl index-newsbox item" id="news">
	<div class="til">
		<span class="c1">资讯中心</span>|<span class="f2">News</span>
        <a href="{% url 'new:new_list' %}" target="_blank" class="fr c1">More+</a>
	</div>
	<div class="newsboxi">
		<div class="newsboxi-b">
            <a href="http://gsxt.ngsh.gov.cn:9080/ECPS/company/detail.jspx?id=2AE01080E2BDD2EDDA6A4DFF633722E7&jyzk=jyzc" target="_blank">
                <h2>星之羽网络科技有限责任公司成立</h2>
            </a>
			<p>
				2019年1月29日，星之羽网络科技有限责任公司成功在宁夏正式挂牌
                <br>
                企业简称：星之羽。
                <br>
                企业代码：91640522MA771D71XT。

			</p>
			<a href="" target="_blank" class="btn-look">查看</a>
		</div>
		<div class="newsboxi-b">
			<ul>
                {% for new in news %}
                    <li class="nt"><a href="{% url 'new:article' new.classify new.id %}" target="_blank">{{ new.title | slice:':5' }}</a>
                        <span>[{{ new.add_time }}]</span></li>
                {% endfor %}

			</ul>
		</div>
	</div>
</div>
<div class="index-team item" id="team">
	<div class="font c1">
		<span class="f2 fs36">Our Team</span><br>
		<span class="f2 fs36">&amp;</span><br>
		<span class="f3 fs20">我们的团队</span>
		<p class="lh56 f1 fs16">
			我们多位资深工程师全天候保证平台平稳运营
		</p>
	</div>
	<div id="marquee2" class="marqueeleft-2">
		<div style="width:8000px">
			<ul id="marquee2_1">
                {% for each in team %}
                <li><img src="{{ MEDIA_URL }}{{ each.photo }}">
				<p class="name">
					{{ each.name }}
				</p>
				<p class="han">
					{{ each.introduce }}
				</p>
				</li>
                {% endfor %}

			</ul>
			<ul id="marquee2_2">
			</ul>
		</div>
		<script type="text/javascript">marqueeStart(2,"left");</script>
	</div>
</div>
<div class="index-partners wl item" id="par">
	<div class="box-end-2 icons">
	</div>
	<div class="font">
		<span class="f2 fs36">Partners</span><br>
		<span class="f2 fs36">&amp;</span><br>
		<span class="f3 fs20 c2">合作伙伴</span>
	</div>
	<div class="par_mainbox">
        {% for partner in partners %}
		    <div class="par-imgbox">
			<div class="par-img">
				<a href="#" target="_blank"><img src="{{ MEDIA_URL }}{{ partner.image }}"></a>
			</div>
			{{ partner.name }}
		</div>
        {% endfor %}
	</div>
</div>
<div id="go">
	<div class="f-box">
		<a href="#about" class="fon1"><span>介绍</span><em></em></a>
	</div>
	<div class="f-box">
		<a href="#advantage" class="fon1"><span>优势</span><em></em></a>
	</div>
	<div class="f-box">
		<a href="#serve" class="fon1"><span>服务</span><em></em></a>
	</div>
	<div class="f-box">
		<a href="#news" class="fon1"><span>资讯</span><em></em></a>
	</div>
	<div class="f-box">
		<a href="#team" class="fon1"><span>团队</span><em></em></a>
	</div>
	<div class="f-box">
		<a href="#par" class="fon1"><span>合作</span><em></em></a>
	</div>
</div>
<script type="text/javascript" language="javascript">$(document).ready(function(){$(".fon1").anchorGoWhere({target:1})});</script>
<div id="rig-suspend">
	<div class="toptil">
		<p class="fs16">
			{{ information.name | slice:':5'}}
		</p>
		<p style="color:#000;font-size:16px">
            {{ information.mobile }}
		</p>
	</div>
	<div class="colbox sus-qq">
		<a href="#">QQ咨询</a><a class="block-qq" target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin={{ information.qq }}&site=qq&menu=yes">{{ information.qq }}</a>
	</div>
	<div class="colbox sus-phone">
		<a href="{{ information.email }}">邮箱地址</a>
		<em>{{ information.email }}</em>
	</div>
	<div class="colbox sus-address">
		<a href="content/about.html">公司地址</a>
	</div>
	<div class="colbox sus-news">
		<a href="{% url 'new:new_list' %}">新闻动态</a>
	</div>
	<div class="colbox sus-about">
		<a href="content/about.html">关于我们</a>
	</div>
</div>
</body>
{% endblock %}

templates/new.html
{% extends 'base.html' %}
{% load static %}
{% block title %}新闻动态{% endblock %}

{% block body %}
<body>
<script type="text/javascript">
    $("#navigate a").each(function () {
        var link = this.href.toLowerCase().substring(0,this.href.length-5);
        if (document.location.href.toLocaleLowerCase().indexOf(link) > -1) {
            $("#navigate a").removeClass("sel");
            $(this).addClass("sel");
        }
    });
</script>
<!--/Header-->
<div class="banner" style="background: url({% static 'images/news_banner.jpg' %}) center no-repeat;height:400px">
</div>
<!--公告联系方式-->
<div class="index-graybox item" id="flow">
	<div class="wl index-graycon">
		<!--制作流程-->
		<div class="index-flow">
			<ul>
				<li><em class="icons early"></em>前期策划沟通<br/>COMMUNICATIONS</li>
				<li><em class="icons design"></em>视觉及交互设计<br/>VISUAL AND DESIGN</li>
				<li><em class="icons html"></em>前端表现及功能开发<br/>HTML/CSS/TLoan</li>
				<li><em class="icons test"></em>测试调整阶段<br/>ADJUSTMENT/TEST</li>
			</ul>
		</div>
		<!--制作流程end-->
	</div>
</div>
<!--公告联系方式end-->
<div class="n-til">
	<span class="span">{{ article.get_classify_display }}</span>
</div>
<div class="n-main">
	<div class="n-title">
		<h2>{{ article.title }}</h2>
		<span>发布时间：{{ article.add_time }}
		</span>
		<span>来源：本站</span>
		<span>作者：{{ article.author }}</span>
		<span>浏览量：{{ article.read_num }}</span>
	</div>
	<div class="n-content">
        {{ article.content |safe }}
	</div>
	<div class="n-add">
		<span class="n-prev">上一篇：<a href="news/show-311.html"></a></span>
        <span class="n-next">下一篇：</span>
	</div>
</div>
</body>
{% endblock %}

templates/new_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}新闻动态{% endblock %}

{% block body %}
<body>
<script type="text/javascript">
    $("#navigate a").each(function () {
        var link = this.href.toLowerCase().substring(0,this.href.length-5);
        if (document.location.href.toLocaleLowerCase().indexOf(link) > -1) {
            $("#navigate a").removeClass("sel");
            $(this).addClass("sel");
        }
    });
</script>
<!--/Header-->
<div class="banner" style="background: url({% static 'images/news_banner.jpg' %}) center no-repeat;height:400px">
</div>
<!--内容列-->
<div class="wl newsbox" id="till">
	<div class="til">
		<span class="span"><a href="{% url 'new:new_list' %}">新闻资讯 ></a></span>
		<ul id="menu1">
            {% for key,value in classifies.items %}
                <li {% ifequal key request.GET.classify %}class="con"{% endifequal %}>
                    <a href="?classify={{ key }}">{{ value }}</a>
                </li>
            {% endfor %}
		</ul>
	</div>
	<div class="main" id="main1">
		<ul class="block">
			<!--取得一个分页DataTable-->
            {% for new in news.object_list %}
			<li>
			<a href="{% url 'new:article' new.classify new.id %}" target="_blank">
			    <h2>{{ new.title }}</h2>
			</a>
			<div class="inside">
				<div class="picbox">
					<img src="{{ MEDIA_URL }}{{ new.image }}" style="width: 137px; height: 122px;"/>
				</div>
				<p>
					{{ new.intro }}
				</p>
				<span class="views">阅读({{ new.read_num }})</span><span class="datetime">{{ new.add_time.date }}</span>
			</div>
			</li>
            {% endfor %}
			<div id="page">
{#				<span>共<font>96</font>条记录 </span>#}
{#                <span class="disabled">&lt;</span>#}
{#                <span class="current">1</span>#}
{#                <a href="#">2</a>#}
{#                <a href="#">3</a>#}
{#                <a class="np" href="{{ news }}">&gt;</a>#}

                {{ news.render }}
			</div>
		</ul>
	</div>
</div>
</body>
{% endblock %}